---
title: "auto_plot MS1_ratio&scan"
output: html_document
date: "2023-01-04"
---

```{r 1merge}
library(tidyverse)
library(readxl)
library(openxlsx)
# Find all .csv files
files <- dir("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/byonic", recursive=TRUE, full.names=TRUE, pattern="\\.xlsx$")

# Apply the function to all files.
result <- files %>% lapply(read_excel, sheet = 2) %>% bind_rows
#%>% rename(Peptide = `Peptide\n< ProteinMetrics Confidential >`), col_types = "text"
colnames(result) <-  c("Query", "Protein_Rank", "Peptide", "Glycans_NHFAGNa", "Modification", "Observed_m_z", "z", "Observed_MH", "Calcmass", "Offbyerror", "Masserror", "StartingPosition", "Cleavage", "Score", "Delta", "DeltaMod", "LogProb", "uniquePeptides", "ProteinName", "ProteinDBnum","Comment", "Scannum", "ScanTime")
result1 = result %>% filter(!(startsWith(ProteinName, ">Reverse >")))
write.xlsx(result1, "1combine.xlsx")
```


```{r 2heavy_extract}
heavy_list = list.files(pattern = "1combine.xlsx", full.names = TRUE)  
data_heavy = heavy_list %>% lapply(read_excel) %>% bind_rows #, col_names = TRUE, skip = 1, sheet = 1, , col_types = "text"
funb <- function(x) gsub("[^0-9A-Za-z///']", "", x)
data_mutate = data_heavy %>% mutate(modi = funb(.[[5]])) 
toMatch <- c('198','214','166','167')
match_heavy <- data_mutate %>% filter(., grepl(paste(toMatch, collapse="|"), modi)) %>% select(-modi) %>% arrange(Peptide, desc(Score))
#write.xlsx(match_heavy, "2.1heavy_match.xlsx")

# {r 2.2light_extract}
light_list = list.files(pattern = "1combine.xlsx", full.names = TRUE)  
data_light = light_list %>% lapply(read_excel) %>% bind_rows #, col_names = TRUE, skip = 1, sheet = 1, , col_types = "text"
funb <- function(x) gsub("[^0-9A-Za-z///']", "", x)
data_mutate = data_light %>% mutate(modi = funb(.[[5]])) 
toMatch <- c('188','204','156','157')
match_light <- data_mutate %>% filter(., grepl(paste(toMatch, collapse="|"), modi)) %>% select(-modi) %>% arrange(Peptide, desc(Score))
#write.xlsx(match_light, "2.2light_match.xlsx")

```

```{r 3pair_match}
library(tidyverse)
library(readxl)
library(openxlsx)
library(stringr)
funb <- function(x) gsub("[^a-zA-Z]", "", x)
heavy = match_heavy %>% mutate(peptide1 = funb(.[[3]])) %>% mutate(pep1 = str_sub(peptide1, 2, -2)) %>% separate(Comment, into=c("raw","other"), sep = "[.]", remove = FALSE, extra = "drop")
light = match_light %>% mutate(peptide1 = funb(.[[3]])) %>% mutate(pep1 = str_sub(peptide1, 2, -2)) %>% separate(Comment, into=c("raw","other"), sep = "[.]", remove = FALSE, extra = "drop")
merge1 = inner_join(heavy, light, by = c("ProteinName", "pep1", "raw")) %>% filter(abs(Calcmass.x - Calcmass.y) >= 9.998269 & abs(Calcmass.x - Calcmass.y) <= 10.018269) %>% filter(abs(ScanTime.x - ScanTime.y) <= 3) %>% unique(.)
data_enddash = merge1 %>% filter(str_detect(Peptide.x, ".-$")) %>% mutate(sub_pep = str_sub(peptide1.x, 2, -1)) %>% mutate(sub_pep_len = nchar(sub_pep)) %>% filter(sub_pep_len >= 5)
data_other = merge1 %>% filter(!(str_detect(Peptide.x, ".-$"))) %>% mutate(sub_pep = str_sub(peptide1.x, 2, -2)) %>% mutate(sub_pep_len = nchar(sub_pep)) %>% filter(sub_pep_len >= 5)
data_com = rbind(data_enddash, data_other) %>% arrange(pep1, desc(Score.x), desc(Score.y))
write.xlsx(data_com, "HLmatch.xlsx")

```


```{r 4outputfiles}
library(tidyverse)
library(readxl)
library(openxlsx)
library(stringr)
library(RaMS)

source = read_excel("HLmatch.xlsx", sheet = 1) %>% filter(!(startsWith(ProteinName, ">Reverse >")))

source_tmp1 = source %>% select(raw, sub_pep, Calcmass.y, z.x, z.y, ScanTime.x, ScanTime.y) %>% unique(.)
source_tmp2 = source_tmp1 %>% mutate(ScanTimeTemp = (ScanTime.x + ScanTime.y)/2) %>% group_by(raw, sub_pep, Calcmass.y) %>% summarise(ScanTimeMean = mean(ScanTimeTemp))
source_tmp3 = left_join(source_tmp2, source_tmp1[,-c(6,7)], by = c("sub_pep", "Calcmass.y")) %>% unique(.) %>% pivot_longer(., cols = starts_with("z."), names_to = "zn", values_to = "Z") %>% select(-zn) %>% unique(.) %>% pivot_longer(., cols = starts_with("raw."), names_to = "rawn", values_to = "raw") %>% select(-rawn) %>% unique(.)
source_final = left_join(source_tmp2, source_tmp3[,-c(3)], by = c("raw", "sub_pep", "Calcmass.y")) %>% unique(.) %>% arrange(sub_pep, raw)
write.xlsx(source_final, "HLmatch_3min.xlsx")

source_temp4.1 = source %>% group_by(ProteinName, pep1, StartingPosition.x, Peptide.x, Peptide.y, Modification.x, Modification.y, z.x, raw) %>% summarise(maxScore = max(Score.x)) %>% ungroup(.)
source_temp4.2 = source_temp4.1 %>% arrange(pep1, raw, z.x) 
write.xlsx(source_temp4.2, "output_peptides.xlsx")

source_temp4.3 = source %>% group_by(ProteinName, pep1, StartingPosition.x) %>% summarise(maxScore = max(Score.x)) %>% ungroup(.)
source_temp4.4 = source_temp4.3 %>% arrange(pep1) 
write.xlsx(source_temp4.4, "output_proteins.xlsx")

```
```{r 4.1diff_outputfiles}

#HLmatch_diffsource1 = read_excel("HLmatch_1min.xlsx", sheet = 1) 
#HLmatch_diffsource3 = read_excel("HLmatch_3min.xlsx", sheet = 1)
#source_final = anti_join(HLmatch_diffsource3, HLmatch_diffsource1, by="sub_pep")

```


```{r 5export}
total_row = nrow(source_final)
mainDir = './results/individual'

for (i in 1:total_row) # check rows.
{
subDir = paste(source_final$sub_pep[i], 'z',source_final$Z[i], source_final$raw[i],'row', i, sep = '_')
plotname = paste(source_final$sub_pep[i], 'z',source_final$Z[i], source_final$raw[i], sep = '_')
dir.create(file.path(mainDir, subDir))
#setwd(file.path(mainDir, subDir))

raw = paste(source_final$raw[i], '.mzXML', sep = '')
msdata <- grabMSdata(files = paste('./mzxml/',raw, sep = ''), grab_what = c("MS1"))
calculatedmass = source_final$Calcmass.y[i] # [M+H]+
z = source_final$Z[i]
m = (calculatedmass - 1.00728 + z*1.00728)/z # L m/z
diff = 10.008269
retentiontime =  source_final$ScanTimeMean[i]

df = msdata$MS1 %>% filter(abs(rt-retentiontime) < 1.25) %>% select(-filename) 

df1 = df %>% filter(abs((mz - m)/m*10^6) <= 10) 
df2 = df %>% filter(abs((mz - (m + 1/z))/(m + 1/z)*10^6) <= 10) 
df3 = df %>% filter(abs((mz - (m + 2/z))/(m + 2/z)*10^6) <= 10) 
df3.1 = df %>% filter(abs((mz - (m + 3/z))/(m + 3/z)*10^6) <= 10) 
df3.2 = df %>% filter(abs((mz - (m + 4/z))/(m + 4/z)*10^6) <= 10) 
df3.3 = df %>% filter(abs((mz - (m + 5/z))/(m + 5/z)*10^6) <= 10) 

df4 = df %>% filter(abs((mz - (m + diff/z))/(m + diff/z)*10^6) <= 10) 
df5 = df %>% filter(abs((mz - (m + diff/z + 1/z))/(m + diff/z + 1/z)*10^6) <= 10) 
df6 = df %>% filter(abs((mz - (m + diff/z + 2/z))/(m + diff/z + 2/z)*10^6) <= 10) 
df6.1 = df %>% filter(abs((mz - (m + diff/z + 3/z))/(m + diff/z + 3/z)*10^6) <= 10) 
df6.2 = df %>% filter(abs((mz - (m + diff/z + 4/z))/(m + diff/z + 4/z)*10^6) <= 10) 
df6.3 = df %>% filter(abs((mz - (m + diff/z + 5/z))/(m + diff/z + 5/z)*10^6) <= 10) 

df_org = inner_join(df1, df2, by = c("rt")) %>% inner_join(., df3, by = c("rt")) %>% inner_join(., df4, by = c("rt")) %>% inner_join(., df5, by = c("rt")) %>% inner_join(., df6, by = c("rt"))

colnames(df_org) <- c("rt", "mz1", "int1", "mz2", "int2", "mz3", "int3", "mz4", "int4", "mz5", "int5", "mz6", "int6")

df_org = df_org %>% mutate(mz1_avg = mean(mz1), mz4_avg = mean(mz4)) %>% mutate(error = (mz1_avg - m) / m * 10^6, error4 = (mz4_avg-(m + diff/z))/(m + diff/z) * 10^6) 

write.xlsx(df_org, file = paste(mainDir, subDir,"df_filter.xlsx", sep = "/"))

df_org1 = inner_join(df1, df2, by = c("rt")) %>% inner_join(., df3, by = c("rt")) %>% inner_join(., df4, by = c("rt")) %>% inner_join(., df5, by = c("rt")) %>% inner_join(., df6, by = c("rt")) %>% left_join(., df3.1, by = c("rt")) %>% left_join(., df3.2, by = c("rt")) %>% left_join(., df3.3, by = c("rt")) %>% left_join(., df6.1, by = c("rt")) %>% left_join(., df6.2, by = c("rt")) %>% left_join(., df6.3, by = c("rt"))
colnames(df_org1) <- c("rt", "mz1", "int1", "mz2", "int2", "mz3", "int3", "mz7", "int7", "mz8", "int8", "mz9", "int9", "mz4", "int4","mz5", "int5","mz6", "int6","mz10", "int10","mz11", "int11","mz12", "int12")

df_plot = df_org1 %>% mutate(mz1.1 = int1 / int1, mz1.2 = int2 / int1, mz1.3 = int3 / int1, mz1.4 = int4 / int1, mz1.5 = int5 / int1, mz1.6 = int6 / int1, mz2.1 = int7 / int1, mz2.2 = int8 / int1, mz2.3 = int9 / int1, mz2.4 = int10 / int1, mz2.5 = int11 / int1, mz2.6 = int12 / int1) %>% select(mz1.1, mz1.2, mz1.3, mz1.4, mz1.5, mz1.6, mz2.1, mz2.2, mz2.3, mz2.4, mz2.5, mz2.6) 

df_plot1 = df_plot %>% pivot_longer(c("mz1.1":"mz2.6"), names_to = "mz", values_to = "ratio")

write.xlsx(df_plot, file = paste(mainDir, subDir, "ratio_plot.xlsx", sep = "/"))

num1 = round(m, 4)
num2 = round(m + 1/z, 4)
num3 = round(m + 2/z, 4)
num4 = round(m + 3/z, 4)
num5 = round(m + 4/z, 4)
num6 = round(m + 5/z, 4)
num7 = round(m + diff/z, 4)
num8 = round(m + diff/z + 1/z, 4)
num9 = round(m + diff/z + 2/z, 4)
num10 = round(m + diff/z + 3/z, 4)
num11 = round(m + diff/z + 4/z, 4)
num12 = round(m + diff/z + 5/z, 4)

library(ggplot2)
if (nrow(df_plot1) == 0) {
  next
} else {
ggplot(df_plot1, aes(x=mz, y=ratio)) + 
  geom_jitter(position = position_jitter(0.2), color = "darkgray")+
  stat_summary(fun.data="mean_sdl", fun.args = list(mult=1), geom="crossbar", width=0.5) +
  ylim(0,2) +
  xlab("m/z") +
  ylab("H/L Ratio")+
  scale_x_discrete(breaks = c("mz1.1", "mz1.2", "mz1.3", "mz1.4", "mz1.5", "mz1.6", "mz2.1", "mz2.2", "mz2.3", "mz2.4", "mz2.5", "mz2.6"), labels = c(`num1`, `num2`, `num3`,`num4`,`num5`,`num6`,`num7`,`num8`,`num9`,`num10`,`num11`,`num12`))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle(paste(plotname))
  
ggsave(filename = paste(mainDir, subDir, "mzratioPlot.pdf", sep = '/'))
}

tmp = df_org1 %>% select(rt) %>% inner_join(., df, by = "rt") 
rts = split(tmp, f = tmp$rt)
mx = length(rts)
rg_min = round(m - 5, 0)
rg_max = round(m + diff/z + 5, 0)

t_ms1 = c(rbind(df_org1$mz1, df_org1$mz2, df_org1$mz3, df_org1$mz4,df_org1$mz5,df_org1$mz6))
t_ms2 = c(rbind(df_org1$mz7, df_org1$mz8, df_org1$mz9, df_org1$mz10, df_org1$mz11, df_org1$mz12))

library(ggrepel)

if (mx == 0) {
  next
} else {
for (j in 1:mx)
{
  dfa = rts[[j]] %>% filter(mz > rg_min & mz < rg_max) %>% mutate(color = case_when(
    mz %in% t_ms1 ~ 'red',
    mz %in% t_ms2 ~ 'green',
    TRUE ~ 'black'
  ))
  standard_int = dfa %>% filter(!(color == 'black')) %>% select(int) %>% max(.)
  dfb = dfa %>% mutate(int_norm = int / standard_int * 100) %>% mutate(int_fi = ifelse(int_norm > 150, 150, int_norm)) %>% mutate(combo = paste(round(mz,4), round(int,0), sep = ", I:"))
  
  library(ggrepel)
  ggplot(dfb %>% filter(color == "black"))+
  geom_bar(aes(x=mz, y=int_fi), stat = "identity", color = "#000000", width = 0.01)+
  geom_bar(data = dfb %>% filter(color == "red"), aes(x=mz, y=int_fi), stat = "identity", color = "red", width = 0.01)+
  geom_bar(data = dfb %>% filter(color == "green"), aes(x=mz, y=int_fi), stat = "identity", color = "green", width = 0.01)+
  geom_label_repel(data = dfb %>% filter(color != "black"), aes(x=mz, y=int_fi, label = combo), na.rm = T, segment.color = "#C55A11", color = "#C55A11", segment.size = 0.1)+
  scale_x_continuous(expand = expansion(mult = c(0, 0)), breaks = seq(rg_min, rg_max, 5)) + 
  scale_y_continuous(expand = expansion(mult = c(0, 0)), breaks = seq(0, 150, 10))+
  coord_cartesian(xlim=c(rg_min, rg_max), ylim = c(0, 150))+
  theme_classic()+
  theme(legend.position = "none")+
  theme(axis.line = element_line(size = 0.1, colour = "black"))+
  xlab(NULL)+
  ylab(NULL)+
  ggtitle(paste(plotname, round(as.numeric(names(rts)[j]), digits = 4), "min", sep = "_"))
  
  filepath = paste(mainDir, subDir, sep = '/')
  ggsave(paste(filepath, "/scan_", j, ".pdf",sep=""))
  #dev.off()
}
}
}

```


```{r 6mergePDF}
library(qpdf)

# 1 ratioPlot
pdfFiles <- dir("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/individual", recursive=TRUE, full.names=TRUE, pattern="(mzratioPlot)+(.pdf)")

n = length(pdfFiles)

if (n %% 500 == 0) {
  round = n %/%500
} else {
  round = n %/%500 + 1
}

for (r in 1:round) {
  left = (r-1)*500 + 1
  right = r*500
  if (right > n) {
    right = n
  }
  qpdf::pdf_combine(input = pdfFiles[left:right], output = paste("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/output1_ratios", r, ".pdf", sep = ""))
}

# 2 first_ms1_example
ms1Files <- dir("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/individual", recursive=TRUE, full.names=TRUE, pattern="(scan_1)+(.pdf)")

n = length(ms1Files)

if (n %% 500 == 0) {
  round = n %/%500
} else {
  round = n %/%500 + 1
}

for (r in 1:round) {
  left = (r-1)*500 + 1
  right = r*500
  if (right > n) {
    right = n
  }
  qpdf::pdf_combine(input = ms1Files[left:right], output = paste("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/output4_ms1example", r, ".pdf", sep = ""))
}

# 3 Scans
ScanFiles <- dir("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/individual", recursive=TRUE, full.names=TRUE, pattern="scan_\\d{1}|d{2}|d{3}\\.pdf") 

n = length(ScanFiles)

if (n %% 500 == 0) {
  round = n %/%500
} else {
  round = n %/%500 + 1
}

for (r in 1:round) {
  left = (r-1)*500 + 1
  right = r*500
  if (right > n) {
    right = n
  }
  qpdf::pdf_combine(input = ScanFiles[left:right], output = paste("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/scans/output2_500scans", r, ".pdf", sep = ""))
}


# 4 ratio+scans
AllFiles <- dir("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/individual", recursive=TRUE, full.names=TRUE, pattern="\\.pdf$")

n = length(AllFiles)

if (n %% 500 == 0) {
  round = n %/%500
} else {
  round = n %/%500 + 1
}

for (r in 1:round) {
  left = (r-1)*500 + 1
  right = r*500
  if (right > n) {
    right = n
  }
  qpdf::pdf_combine(input = AllFiles[left:right], output = paste("D:/Tom_Lin/searched/20220812_lin_1_30_3and5_repeat/results/combined/output3_500combined", r, ".pdf", sep = ""))
}

```


```{r 7pdf_statistics}
pdf = as_tibble(pdfFiles) 
tmp = pdf %>% separate(value, into = c(NA,NA,NA,NA,NA,NA,"file",NA), sep = "[/]") %>% separate(file, into = c("pep1",NA, "z","s1", "s2", "s3", "s4", "s5", "s6"), sep = "[_]") %>% unite(col = "raw", c("s1", "s2", "s3", "s4", "s5", "s6"), sep = "_") %>% mutate(MS1pair = "Yes") %>% mutate(z = as.numeric(z)) 


final = left_join(source_temp4.2, tmp, by = c("raw", "pep1", "z.x" = "z")) %>% mutate(MS1pair = replace_na(MS1pair, "No")) 
#write.xlsx(final, "MS1pair.xlsx")

tmp2 = pdf %>% separate(value, into = c("f1","f2","f3","f4","f5","f6","f7",NA), sep = "[/]") %>% mutate(f8 = "df_filter.xlsx") %>% unite(col = "raw", c("f1", "f2", "f3", "f4", "f5", "f6","f7","f8"), sep = "/") 
len1 = nrow(tmp2)
lst = vector('list', len1)

for (i in 1:len1) {
  data = read_excel(tmp2$raw[i]) %>% mutate(ratio = (int4 + int5 + int6)/(int1 + int2 + int3))
  ratioAverage = mean(data$ratio)
  #sd = list()
  sd = sd(data$ratio)
  #number = list()
  number = nrow(data)
  lst[[i]] = data.frame(ratioAverage, sd, number, tmp2$raw[i])
}

df_ratio <- do.call("rbind", lst) %>% separate(tmp2.raw.i., into = c(NA,NA,NA,NA,NA,NA,"file",NA), sep = "[/]") %>% separate(file, into = c("pep1",NA, "z","s1", "s2", "s3", "s4", "s5", "s6"), sep = "[_]") %>% unite(col = "raw", c("s1", "s2", "s3", "s4", "s5", "s6"), sep = "_") %>% mutate(z = as.numeric(z))
colnames(df_ratio) <-  c("ratioAverage", "sd", "number", "pep1", "z.x", "raw")
#write.xlsx(df_ratio, "ratio_summary.xlsx")

sum_temp1 = left_join(final, df_ratio, by = c("pep1", "z.x", "raw")) %>% mutate(HL_MS2 = "Yes") %>% unique(.)
colnames(sum_temp1) <-  c("ProteinName", "peptide","StartingPosition", "Peptide.H","Peptide.L","Modification.H","Modification.L","z","raw","maxScore","MS1pair?","HL_ratio","ratio_sd","n_MS1pairs", "HL_MS2?") 
sum_temp2 = sum_temp1 %>% select("ProteinName", "peptide","StartingPosition", "Peptide.H","Peptide.L","z","raw","maxScore", "HL_MS2?", "MS1pair?","HL_ratio","n_MS1pairs", "ratio_sd") %>% unique(.)

write.xlsx(sum_temp2, "output_summary.xlsx", keepNA = TRUE, na.string = "NA")

```
